export const PERMISSIONS = {
  READ_SETTING: 'READ_SETTING',
  UPDATE_SETTING: 'UPDATE_SETTING',
  APPROVE_SELLER: 'APPROVE_SELLER',
  MANAGE_CATALOG: 'MANAGE_CATALOG',
  MANAGE_CMS: 'MANAGE_CMS',
  READ_BID: 'READ_BID',
  UPDATE_BID: 'UPDATE_BID',
  READ_AUCTION: 'READ_AUCTION',
  CREATE_AUCTION: 'CREATE_AUCTION',
  UPDATE_AUCTION: 'UPDATE_AUCTION',
  DELETE_AUCTION: 'DELETE_AUCTION',
  VIEW_REPORTS: 'VIEW_REPORTS',
  VIEW_AUDIT_LOGS: 'VIEW_AUDIT_LOGS',
};

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];
